#!/bin/sh

DEV_RECIPES=~/.config/Franz/recipes/dev

mklink()
{
    RECIPE=$1
    if [ -d $DEV_RECIPES/$RECIPE ]; then
        ln -s $RECIPE $DEV_RECIPES/$RECIPE
    fi
}

mkdir -p $DEV_RECIPES
mklink android-messages
mklink google-play-music
mklink netflix
