#!/bin/bash

DEV_RECIPES=~/.config/Franz/recipes/dev

mklink()
{
    RECIPE=$1
    TARGET="$DEV_RECIPES/$RECIPE"
    if [ -d $TARGET ] || [ -L $TARGET ]; then
        echo "Skipping $RECIPE"
    else
        echo "Installing $RECIPE"
        ln -s $(readlink -m $RECIPE) $DEV_RECIPES/$RECIPE
    fi
}

mkdir -p $DEV_RECIPES
for RECIPE in $(ls -d ./*/ | cut -d'/' -f 2); do
    mklink $RECIPE
done
